"""Initial

Revision ID: 1537bef8f225
Revises: 
Create Date: 2026-06-19 12:09:15.588694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1537bef8f225'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('attachment_url', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('recurring_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('tasks', 'recurring_type')
    op.drop_column('tasks', 'is_recurring')
    op.drop_column('tasks', 'attachment_url')
    op.drop_column('notifications', 'created_at')
    # ### end Alembic commands ###
