"""note attachment

Revision ID: 7c78d693e99f
Revises: cf074f97545f
Create Date: 2026-06-25 07:52:44.700776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c78d693e99f'
down_revision: Union[str, Sequence[str], None] = 'cf074f97545f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'attachment_url')
    # ### end Alembic commands ###
