"""add reminders and notifications

Revision ID: 92de1198decc
Revises: cf95721a52b4
Create Date: 2026-06-22 11:59:45.236303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92de1198decc'
down_revision: Union[str, Sequence[str], None] = 'cf95721a52b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('reminders', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('reminders', sa.Column('reminder_time', sa.DateTime(), nullable=False))
    op.add_column('reminders', sa.Column('recurring_type', sa.String(length=20), nullable=False))
    op.add_column('reminders', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('reminders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('reminders_task_id_fkey'), 'reminders', type_='foreignkey')
    op.create_foreign_key(None, 'reminders', 'users', ['user_id'], ['id'])
    op.drop_column('reminders', 'remind_at')
    op.drop_column('reminders', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('reminders', sa.Column('remind_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.create_foreign_key(op.f('reminders_task_id_fkey'), 'reminders', 'tasks', ['task_id'], ['id'])
    op.drop_column('reminders', 'created_at')
    op.drop_column('reminders', 'is_completed')
    op.drop_column('reminders', 'recurring_type')
    op.drop_column('reminders', 'reminder_time')
    op.drop_column('reminders', 'title')
    op.drop_column('reminders', 'user_id')
    # ### end Alembic commands ###
